---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ node_apps_location }}"
    state: directory
    mode: '0755'

- name: Git checkout
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ node_apps_location }}"

- name: Install packages based on package.json.
  become: true
  npm:
    path: "{{ node_apps_location }}"

# - name: modify .bashrc  
#   blockinfile:
#     dest: ~/.bashrc
#     block: |
#       export DB_HOST='192.168.3.215'
#       export DB_USER='user'
#       export DB_PASSWORD='example'
#     insertafter: EOF
#     create: yes
- name: end example Node.js app.
  command: C:\>netstat -ano | find "LISTENING" | find "8000"
  
- name: Start example Node.js app.
  command: npm run start
  args:
    chdir: "{{ node_apps_location }}"
  environment:
    DB_SCHEMA: "{{ db_name }}"
    DB_HOST: "{{ db_host }}"
    DB_USER: "{{ db_user }}"
    DB_PASSWORD: "{{ db_password }}"
