---
- hosts: all
  become: true
  gather_facts: no
  vars:
    node_apps_location: /usr/local/app
    git_repo: https://github.com/EAS-Clark/DiscordBot-Images.git
    db_password: 'example'
    db_host: '192.168.3.215'
    db_user: 'user'
    db_name: 'db'
    
  vars_files:
    - vars/main.yml
  

  roles:
    - pymysql
    - { role: geerlingguy.mysql, become: yes , when: '"mysql" in group_names'}
    - { role: mysql_query, when: '"mysql" in group_names'}
    - { role: nodeJs, when: '"vm" in group_names'}
    - { role: appInstall, when: '"vm" in group_names'}

