---
- name: remove bind-address and add bind-address = '0.0.0.0'
  lineinfile:
    line: bind-address = '0.0.0.0'
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    search_string: bind-address
    state: present

- name: restart mytsql service
  command: service mysql restart
  
- name: drop image_HTML_URl table
  community.mysql.mysql_query:
    login_db: db
    query: DROP TABLE IF EXISTS image_HTML_URl;DROP TABLE IF EXISTS image_HTML_URl;

- name: Creating the table image_HTML_URl
  community.mysql.mysql_query:
    login_db: db
    query:
    - CREATE TABLE image_HTML_URl (id INT AUTO_INCREMENT NOT NULL, HTML_URL VARCHAR(300) NOT NULL,Name_of_image VARCHAR(128) NOT NULL, tag VARCHAR(128) NOT NULL,PRIMARY KEY (`id`));

- name: Adding data in to image_HTML_URl
  community.mysql.mysql_query:
    login_db: db
    query: INSERT INTO image_HTML_URl (HTML_URL, Name_of_image, tag) VALUES ('/uploads/Billy_puppy.PNG', 'Billy_puppy', 'dog'), ('test2', 'pic', 'cat');

